### ISSUE TITLE
What is the point of this repository?

### ISSUE THREAD

**Issue by tpietzsch** [imglib/imglib2-introductory-workshop#1]
As far as I can see, this is a copy of https://github.com/StephanPreibisch/imglib2-introduction
but not really, and it is missing the pom and the README?

**Comment by ctrueden** [comment]
@etarena Do you remember?

@StephanPreibisch Would it make sense to move `StephanPreibisch/imglib2-introduction` to the `imglib` org?

**Comment by etadobson** [comment]
@ctrueden Honestly.  I do not remember.  This was AGES ago... back when I first started.

**Comment by tpietzsch** [comment]
Can I just remove/replace this then?

**Comment by etadobson** [comment]
@tpietzsch that's a 'yes' for me.

**Comment by tpietzsch** [comment]
👍
